Make title in ClientboundOpenScreenPacket a component
GeyserMC/MCProtocolLib pull request #688
Opened 2022-02-19 14:09 UTC by MCMDEV

This should be a component and not a string. Atleast it's this way in vanilla and paper.

2022-02-19 14:52 UTC, RednedEpic requested changes

2022-02-19 14:52 UTC, RednedEpic commented on src/main/java/com/github/steveice10/mc/protocol/packet/ingame/clientbound/inventory/ClientboundOpenScreenPacket.java
> +    private final @NonNull Component name;
This is going to break ABI. I suggest renaming this parameter to `title` and adding (deprecated) getName and setName methods using strings so code currently expecting this to be a string does not break.

2022-03-05 21:53 UTC, Camotoy approved these changes

2022-03-05 21:56 UTC, merged

2022-03-05 21:57 UTC, Camotoy commented
Thanks!