Fix rain when set by GameEvent directly
GeyserMC/MCProtocolLib pull request #730
Opened 2023-03-21 04:16 UTC by Kas-tle

Should fix https://github.com/GeyserMC/Geyser/issues/3611

As documented on the protocol wiki, stop rain (1) should come before start rain (2) https://wiki.vg/Protocol#Game_Event. Initially I thought that this could be related to our handling of rain strength (7) (see https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaGameEventTranslator.java#L72-L87). In fact, that code was working so well that it was masking this issue entirely.

For context, this issue was primarily experienced when the weather lock flag was set to clear with world guard. In this scenario, only a single Game Event packet is sent to set the weather to clear. But given we had these switched, it would instead lead to endless rain for the Bedrock Client.

In contrast, the Vanilla weather command gave the appearance of working fine. It only appeared this way, however, because the rain strength logic effectively ends up overriding the initial packet sent that indicates clear weather to the bedrock client.

2023-03-21 05:38 UTC, Camotoy requested changes
I don't think this is the right solution. I took a look through the Minecraft source, and in ClientboundGameEventPacket, START_RAIN is first.

2023-03-21 05:51 UTC, Kas-tle commented
The packet Game Event packet sent on `/weather clear` has an id of 1, while `/weather rain` has an id of 2. Isn't the id dictated by the order we set the enum here?

2023-03-21 06:28 UTC, Kas-tle commented
Ok I think I've figured out what is going on here.

If we look in ClientPacketListener in the mojang mapped jar, we see:

```java
else if (type == ClientboundGameEventPacket.START_RAINING) {
            this.level.getLevelData().setRaining(true);
            this.level.setRainLevel(0.0f);
        } else if (type == ClientboundGameEventPacket.STOP_RAINING) {
            this.level.getLevelData().setRaining(false);
            this.level.setRainLevel(1.0f);
        }
```

So... when the client gets START_RAINING, it actually sets the rain level to 0... when it gets STOP_RAINING it sets the rain level to 1... effectively reversing what the logical naming of this would mean...

So I guess it really comes down to semantics. We can either treat their mistake as correct and invert these in Geyser, or we can take the approach of reversing them so the names actually make sense and just comment that we have done so.

It seems they came to this same conclusion in the Paper discord: https://canary.discord.com/channels/289587909051416579/555462289851940864/1066095359404802161

2023-03-21 08:40 UTC, basaigh commented
`if (this.levelData.isRaining()) {
            this.rainLevel += 0.01F;
         } else {
            this.rainLevel -= 0.01F;
         }

         this.rainLevel = Mth.clamp(this.rainLevel, 0.0F, 1.0F);`
It looks to me as if the rain level is set like that to allow for a gradual fade-out of the rain.

2023-03-21 17:08 UTC, Kas-tle commented
Ugh so that might be the intent, but at least spigot seems to set it at the end of the rain storm... like it will ramp down the rain level first, and more or less send """start rain""" (Mojang's words) and rain level 0 at the same time.

2023-03-24 04:17 UTC, Kas-tle commented
Closing in favor of https://github.com/GeyserMC/Geyser/pull/3637
Still might be a good idea to add a short comment about this somewhat non-intuitive naming in the official mappings.

2023-03-24 04:17 UTC, closed without merging