Improve pipeline
GeyserMC/MCProtocolLib pull request #833
Opened 2024-06-18 14:57 UTC by AlexProgrammerDE

This simplifies all pipeline code and ensures some listeners like the sizer are always present. The code already assumed that the sizer is always there and thus causes issues. The sizer can be deactivated still now and has pretty much no performance losses from this. The profit from this PR is that there is less logic with modifying the PR and thus developers interacting with the channel can assume specific things about the order and placements of elements in the pipeline. This will be useful once ViaVersion is supported, and it is expected that certain elements always are in the pipeline and don't change. My plan is to also always have an encryption and compression handler in the pipeline that is controlled via AttributeKeys from netty, but for that first #828 needs to be merged. So this PR only completes the goal partially, but that's fine. PR is ready for review like it is right now.

2024-07-12 04:35 UTC, Konicai requested changes
looking good

2024-07-12 04:35 UTC, Konicai commented on protocol/src/main/java/org/geysermc/mcprotocollib/network/BuiltinFlags.java
> +    public static final Flag<Integer> WRITE_TIMEOUT = new Flag<>("write-timeout", Integer.class);
javadoc that these are in seconds, and that they may be zero or negative for the timeout checks to be disabled

2024-07-12 04:35 UTC, Konicai commented on protocol/src/main/java/org/geysermc/mcprotocollib/network/BuiltinFlags.java
>      public static final Flag<InetSocketAddress> CLIENT_PROXIED_ADDRESS = new Flag<>("client-proxied-address", InetSocketAddress.class);
javadoc that null == support disabled

2024-07-12 04:35 UTC, Konicai commented on protocol/src/main/java/org/geysermc/mcprotocollib/network/tcp/TcpClientSession.java
> +    private void addHAProxySupport(Channel channel) {
i feel like now might be a good time to rename it `initializeHAProxySupport` considering it adds the encoder, sends the message, then removes it.

2024-07-27 19:58 UTC, onebeastchris commented on protocol/src/main/java/org/geysermc/mcprotocollib/network/BuiltinFlags.java
> +
```suggestion
    /**
     * Connection timeout in seconds.
     * Only used by the client.
     */
    public static final Flag<Integer> CLIENT_CONNECT_TIMEOUT = new Flag<>("client-connect-timeout", Integer.class);
    
    /**
     * Read timeout in seconds.
     * Used by both server and client.
     */
    public static final Flag<Integer> READ_TIMEOUT = new Flag<>("read-timeout", Integer.class);
    
    /**
     * Write timeout in seconds.
     * Used by both server and client.
     */
    public static final Flag<Integer> WRITE_TIMEOUT = new Flag<>("write-timeout", Integer.class);

```

2024-07-28 01:08 UTC, Konicai approved these changes

2024-07-28 01:08 UTC, Konicai commented on protocol/src/main/java/org/geysermc/mcprotocollib/network/BuiltinFlags.java
> +     * Write timeout in seconds.
```suggestion
    public static final Flag<Integer> CLIENT_CONNECT_TIMEOUT = new Flag<>("client-connect-timeout", Integer.class);
    
    /**
     * Read timeout in seconds.
     * Used by both server and client.
     */
    public static final Flag<Integer> READ_TIMEOUT = new Flag<>("read-timeout", Integer.class);
    
    /**
     * Write timeout in seconds.
```

2024-07-28 01:08 UTC, Konicai commented on protocol/src/main/java/org/geysermc/mcprotocollib/network/BuiltinFlags.java
> +     * Enables HAProxy protocol support.
```suggestion

    /**
     * Enables HAProxy protocol support.
```

2024-09-08 11:21 UTC, Redned235 approved these changes

2024-09-08 13:28 UTC, onebeastchris approved these changes
last nitpicks, let's merge after these

2024-09-08 13:28 UTC, onebeastchris commented on protocol/src/main/java/org/geysermc/mcprotocollib/network/BuiltinFlags.java
> +     * When this value is not null it means the ip and port the client claims the connection is from.
```suggestion
     * When this value is not null it represents the ip and port the client claims the connection is from.
```

2024-09-08 13:28 UTC, onebeastchris commented on protocol/src/main/java/org/geysermc/mcprotocollib/network/BuiltinFlags.java
> +     * Used by both server and client.
```suggestion
     * Used by both the server and client.
```

2024-09-08 13:28 UTC, onebeastchris commented on protocol/src/main/java/org/geysermc/mcprotocollib/network/BuiltinFlags.java
> +     * Used by both server and client.
```suggestion
     * Used by both the server and client.
```

2024-09-08 13:28 UTC, onebeastchris commented on protocol/src/main/java/org/geysermc/mcprotocollib/network/tcp/TcpServer.java
> +                    if (future1.isSuccess()) {
```suggestion
                this.channel.close().addListener((ChannelFutureListener) future -> {
                    if (future.isSuccess()) {
```

2024-09-08 13:28 UTC, onebeastchris commented on protocol/src/main/java/org/geysermc/mcprotocollib/network/tcp/TcpServer.java
> +                log.error("Failed to bind connection listener.", future1.cause());
```suggestion
        bootstrap.bind().addListener((ChannelFutureListener) future -> {
            if (future.isSuccess()) {
                channel = future.channel();
                if (callback != null) {
                    callback.run();
                }
            } else {
                log.error("Failed to bind connection listener.", future.cause());
```
There's no other variable called future; so this works too (and looks a bit cleaner)

2024-09-08 13:28 UTC, onebeastchris commented on protocol/src/main/java/org/geysermc/mcprotocollib/network/tcp/TcpServer.java
> +                        log.error("Failed to close connection listener.", future1.cause());
```suggestion
                        log.error("Failed to close connection listener.", future.cause());
```

2024-09-08 13:28 UTC, onebeastchris commented on protocol/src/main/java/org/geysermc/mcprotocollib/network/tcp/TcpServer.java
> +                    log.debug("Failed to close connection listener.", future1.cause());
```suggestion
            this.group.shutdownGracefully().addListener(future -> {
                if (!future.isSuccess()) {
                    log.debug("Failed to close connection listener.", future.cause());
```

2024-09-10 07:16 UTC, merged