Update README.md
GeyserMC/MCProtocolLib pull request #844
Opened 2024-07-25 15:56 UTC by waterghost-2046

Provide clear guidance on dependency information and repository configuration to be added to the Maven configuration file

2024-07-26 11:23 UTC, onebeastchris requested changes

2024-07-26 11:23 UTC, onebeastchris commented on README.md
> +        <url>https://repo.opencollab.dev/maven-snapshots/</url>
```suggestion
        <url>https://repo.opencollab.dev/main/</url>
```
This'll include both the snapshots and releases repos

2024-07-26 11:23 UTC, onebeastchris commented on README.md
> +        url 'https://repo.opencollab.dev/maven-snapshots/'
```suggestion
        url 'https://repo.opencollab.dev/main/'
```

2024-07-26 11:23 UTC, onebeastchris commented on README.md
> +    maven("https://repo.opencollab.dev/maven-snapshots/") {
```suggestion
    maven("https://repo.opencollab.dev/main/") {
```

2024-07-28 01:03 UTC, waterghost-2046 commented on README.md
> +    maven("https://repo.opencollab.dev/maven-snapshots/") {
<img width="1630" alt="스크린샷 2024-07-28 오전 10 02 56" src="https://github.com/user-attachments/assets/372d85bc-ee13-45e7-9e9a-b926637b817d">

2024-07-28 01:04 UTC, waterghost-2046 commented
https://repo.opencollab.dev/main/ is null

<img width="1630" alt="스크린샷 2024-07-28 오전 10 02 56" src="https://github.com/user-attachments/assets/1e79a17b-a0ac-414a-a22a-741ce59c4a2e">

2024-07-28 01:12 UTC, onebeastchris commented
You can't browse `main`, as it just redirects to both `releases` and `snapshots`

2024-07-28 02:59 UTC, waterghost-2046 commented
> You can't browse `main`, as it just redirects to both `releases` and `snapshots`

I'm sorry, I tested it and confirmed that it works

2024-07-28 03:42 UTC, Konicai commented on README.md
If we are going to use `main` in the examples, it wouldn't hurt to mention here that the examples below use `main`, which provides access to both release and snapshot repo.

2024-08-20 10:00 UTC, onebeastchris approved these changes

2024-08-20 10:00 UTC, merged